-- Member profile AI score: an LLM-generated assessment of the member's profile
-- (strength/completeness), shown on their profile page. Generated by the `profile-score`
-- Edge Function via Groq and written back with the service role.
--
-- Integrity: members can edit their own profile (RLS "update own profile"), which would let
-- them PATCH ai_profile_score to anything. The guard trigger below freezes the ai_profile_*
-- columns for everyone except the service role, so the AI score can't be self-assigned —
-- same spirit as the AIP anti-cheat.

alter table public.profiles
  add column if not exists ai_profile_score   int,
  add column if not exists ai_profile_summary text,
  add column if not exists ai_profile_at      timestamptz;

create or replace function public.guard_profile_ai_columns()
returns trigger
language plpgsql               -- NOT security definer: we need current_user = the caller's role
as $$
begin
  -- Only the service role (the profile-score Edge Function) may change these columns.
  if current_user is distinct from 'service_role' then
    new.ai_profile_score   := old.ai_profile_score;
    new.ai_profile_summary := old.ai_profile_summary;
    new.ai_profile_at      := old.ai_profile_at;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_guard_profile_ai on public.profiles;
create trigger trg_guard_profile_ai
  before update on public.profiles
  for each row execute function public.guard_profile_ai_columns();
